// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuAYS9eHEEezlgWIyT3khVfY1ZWeJbiJQ',
    appId: '1:1056706439681:web:9caa42ab3fe44b7bebee00',
    messagingSenderId: '1056706439681',
    projectId: 'project-pariwisatatakengon',
    authDomain: 'project-pariwisatatakengon.firebaseapp.com',
    storageBucket: 'project-pariwisatatakengon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HFriLGdDV_JlVajj5YuZgPIhRseVcig',
    appId: '1:1056706439681:android:1bd9e6498a15f39aebee00',
    messagingSenderId: '1056706439681',
    projectId: 'project-pariwisatatakengon',
    storageBucket: 'project-pariwisatatakengon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdVej3Gdd2GTirGQAjNx8LDVTGVTdVpg',
    appId: '1:1056706439681:ios:9567649e9a1c4edeebee00',
    messagingSenderId: '1056706439681',
    projectId: 'project-pariwisatatakengon',
    storageBucket: 'project-pariwisatatakengon.appspot.com',
    iosBundleId: 'com.example.projectPariwisata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdVej3Gdd2GTirGQAjNx8LDVTGVTdVpg',
    appId: '1:1056706439681:ios:9567649e9a1c4edeebee00',
    messagingSenderId: '1056706439681',
    projectId: 'project-pariwisatatakengon',
    storageBucket: 'project-pariwisatatakengon.appspot.com',
    iosBundleId: 'com.example.projectPariwisata',
  );
}
